from collections.abc import AsyncContextManager
from datetime import datetime
from typing import Protocol
from uuid import UUID

from backend.app.domain.models import AuthToken, ChatMessage, ChatSession, User


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def get(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...


class TokenRepository(Protocol):
    async def add(self, token: AuthToken) -> None: ...

    async def get_by_digest(self, token_digest: str) -> AuthToken | None: ...

    async def delete_by_digest(self, token_digest: str) -> None: ...

    async def delete_expired(self, now: datetime) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: ChatSession) -> None: ...

    async def get(self, session_id: UUID) -> ChatSession | None: ...

    async def get_for_user(self, session_id: UUID, user_id: UUID) -> ChatSession | None: ...

    async def list_for_user(self, user_id: UUID) -> list[ChatSession]: ...


class MessageRepository(Protocol):
    async def add(self, message: ChatMessage) -> None: ...

    async def list_for_session(self, session_id: UUID) -> list[ChatMessage]: ...


class ChatUnitOfWork(Protocol, AsyncContextManager["ChatUnitOfWork"]):
    def stage_messages(self, user_message: ChatMessage, assistant_message: ChatMessage) -> None: ...

    def stage_user(self, user: User) -> None: ...

    async def commit(self) -> None: ...
